#! /bin/sh
# $Id: try77,v 1.3 1996/04/17 03:33:17 waite Exp $
# Test an Eli-generated FORTRAN processor

if test $# -lt 1 -o $# -gt 2
then
	echo "Usage: $0 dir [compiler]"
	exit 1
fi

if test ! -d $1
then
	echo "Usage: $0 dir"
	exit 1
fi

for f in `ls $1/*.f`
do
	rm -f ERRS
	${2-./f.exe} $f > ERRS 2>&1
	if test -s ERRS
	then
		cp $f input
		echo "Errors detected in $f"
		echo "$f copied to \"input\""
		exit 1
	fi
done
