/*
 * Created on Jun 3, 2004
 *
 * Workspace-wide Odin preferences (Odin variable page).
 */
package au.edu.mq.ics.plrg.odin;

import org.eclipse.jface.preference.FieldEditorPreferencePage;
import org.eclipse.jface.preference.IPreferenceStore;
import org.eclipse.jface.preference.RadioGroupFieldEditor;
import org.eclipse.ui.IWorkbench;
import org.eclipse.ui.IWorkbenchPreferencePage;

import au.edu.mq.ics.plrg.eli.EDTPlugin;

/**
 * @author asloane
 *
 * Support variable preferences for all Odin projects.
 */
public class VarPreferencePage extends FieldEditorPreferencePage
    implements IWorkbenchPreferencePage {
    
    // Preference keys
    public static final String LOGLEVEL_KEY = "loglevel_key";
    public static final String ERRLEVEL_KEY = "errlevel_key";
    public static final String WARNLEVEL_KEY = "warnlevel_key";
    
    /**
     * Create an Odin preference page.
     */
    public VarPreferencePage() {
        super(GRID);
        IPreferenceStore preferenceStore = EDTPlugin.getDefault().getPreferenceStore();
        setPreferenceStore(preferenceStore);
    }
    
    /**
     * Initialise the page.
     */
    public void init(IWorkbench workbench) {
    }
    
    /**
     * Create the contents of the page.
     */
    protected void createFieldEditors() {
        RadioGroupFieldEditor loglevelField =
            new RadioGroupFieldEditor(
                LOGLEVEL_KEY, "Log level:", 1,
                new String[][] {
                    {"No log information is generated.", "0"},
                    {"Build commands are echoed.", "1"},
                    {"And Odin commands.", "2"},
                    {"And names of objects with errors.", "3"},
                    {"And names of objects generated by tool scripts.", "4"},
                    {"And names of objects generated by internal tools.", "5"},
                    {"And names of objects deleted.", "6"},
                    {"And names of objects touched by broadcast.", "7"}
                },
                getFieldEditorParent());
        addField(loglevelField);
        
        RadioGroupFieldEditor errlevelField =
            new RadioGroupFieldEditor(
                ERRLEVEL_KEY, "Error level:", 1,
                new String[][] {
                    {"No report.", "0"},
                    {"Status report.", "1"},
                    {"Incremental and status report.", "2"},
                    {"Summary and status report.", "3"},
                    {"Summary, incremental, and status report.", "4"}
                },
                getFieldEditorParent());
        addField(errlevelField);
        
        RadioGroupFieldEditor warnlevelField =
            new RadioGroupFieldEditor(
                WARNLEVEL_KEY, "Warning level:", 1,
                new String[][] {
                    {"No report.", "0"},
                    {"Status report.", "1"},
                    {"Incremental and status report.", "2"},
                    {"Summary and status report.", "3"},
                    {"Summary, incremental, and status report.", "4"}
                },
                getFieldEditorParent());
        addField(warnlevelField);
    }
    
}
